module.exports = {
  apps: [
    {
      name: "onlyoffice",
      script: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
      args: "-NoProfile -Command \"$env:PATH += ';C:\\Program Files\\Docker\\Docker\\resources\\bin'; Set-Location 'D:\\JusConsultus.AI'; docker-compose up -d --remove-orphans 2>&1 | Write-Host; Start-Sleep 5\"",
      cwd: "d:\\JusConsultus.AI",
      instances: 1,
      autorestart: false,
      watch: false,
      max_restarts: 1,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "d:\\JusConsultus.AI\\logs\\onlyoffice-error.log",
      out_file: "d:\\JusConsultus.AI\\logs\\onlyoffice-out.log",
      merge_logs: true,
    },
    {
      name: "jusconsultus",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      cwd: "d:\\JusConsultus.AI",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "d:\\JusConsultus.AI\\logs\\pm2-error.log",
      out_file: "d:\\JusConsultus.AI\\logs\\pm2-out.log",
      merge_logs: true,
    },
    {
      name: "deepsearcher",
      interpreter: "d:\\JusConsultus.AI\\tools\\deepsearcher\\.venv\\Scripts\\python.exe",
      script: "tools/deepsearcher/server.py",
      cwd: "d:\\JusConsultus.AI",
      env: {
        LLM_API_KEY: "sk-9b7acb509e3f4bd3a8b373845378e344",
        LLM_BASE_URL: "https://api.deepseek.com",
        LLM_MODEL: "deepseek-chat",
        DEEPSEARCHER_PORT: "8010",
        LEGAL_DB_ROOT: "d:\\JusConsultus.AI\\data\\legal-database",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "2G",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "d:\\JusConsultus.AI\\logs\\deepsearcher-error.log",
      out_file: "d:\\JusConsultus.AI\\logs\\deepsearcher-out.log",
      merge_logs: true,
    },
    {
      name: "caddy",
      script: "d:\\JusConsultus.AI\\tools\\caddy\\caddy.exe",
      args: "run --config d:\\JusConsultus.AI\\tools\\caddy\\Caddyfile",
      cwd: "d:\\JusConsultus.AI\\tools\\caddy",
      instances: 1,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "d:\\JusConsultus.AI\\logs\\caddy-error.log",
      out_file: "d:\\JusConsultus.AI\\logs\\caddy-out.log",
      merge_logs: true,
    },
    {
      name: "cloudflared",
      script: "d:\\JusConsultus.AI\\tools\\cloudflared\\cloudflared.exe",
      args: "tunnel --config d:\\JusConsultus.AI\\tools\\cloudflared\\config.yml run",
      cwd: "d:\\JusConsultus.AI\\tools\\cloudflared",
      instances: 1,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "d:\\JusConsultus.AI\\logs\\cloudflared-error.log",
      out_file: "d:\\JusConsultus.AI\\logs\\cloudflared-out.log",
      merge_logs: true,
    },
  ],
};
