import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { generateCompletion } from "@/lib/ai/llm";
import {
  DOCUMENT_TEMPLATES,
  type DocumentTemplateKey,
  type TemplateData,
} from "@/lib/documentFormats/scPaperRule";

const DOCUMENT_SYSTEM_PROMPT = `You are JusConsultus AI, an expert Philippine legal document drafter. Generate a professional, complete legal document compliant with Philippine law and the Supreme Court Efficient Use of Paper Rule (A.M. No. 11-9-4-SC).

Rules:
- Follow proper Philippine legal format (proper caption, numbered paragraphs, prayer, signatures)
- Use formal legal language appropriate for Philippine courts
- Add [BRACKET PLACEHOLDERS] for details needing completion
- Cite relevant laws, Rules of Court, and jurisprudence where applicable
- Include Verification if required by the Rules
- Comply with A.M. No. 11-9-4-SC (Arial 14pt, legal paper, SC margins)

Output a complete, ready-to-use document.`;

// Map AI template IDs to local template keys
const TEMPLATE_KEY_MAP: Record<string, DocumentTemplateKey> = {
  complaint: "complaint",
  answer: "answer",
  motion: "motion",
  "motion-dismiss": "motion",
  "motion-summary": "motion",
  reply: "motion",
  demurrer: "motion",
  memorandum: "memorandum",
  "counter-affidavit": "counterAffidavit",
  "motion-quash": "motion",
  "bail-petition": "petition",
  "motion-reconsideration": "motion",
  "motion-reinvestigation": "motion",
  "admin-complaint": "affidavit",
  "answer-admin": "answer",
  "position-paper": "memorandum",
  "petition-review": "petition",
  contract: "contract",
  nda: "nda",
  lease: "lease",
  deed: "deed",
  spa: "spa",
  employment: "contract",
  "demand-letter": "demandLetter",
  "cease-desist": "demandLetter",
  affidavit: "affidavit",
  "affidavit-loss": "affidavit",
  "affidavit-support": "affidavit",
  "affidavit-service": "affidavit",
  "board-resolution": "boardResolution",
  bylaws: "boardResolution",
  minutes: "boardResolution",
  incorporation: "boardResolution",
  "secretary-cert": "affidavit",
};

// Generate via AI API with local template fallback
async function generateDocument(
  documentType: string,
  details: TemplateData,
  tone: string,
  length: string
): Promise<string> {
  const typeKey = documentType.toLowerCase().replace(/\s+/g, "-");

  // Try DeepSeek / LLM generation first (uses LLM_API_KEY + LLM_BASE_URL from .env)
  try {
    const detailsText = Object.entries(details)
      .filter(([k, v]) => v && k !== "prompt")
      .map(([k, v]) => `${k}: ${v}`)
      .join("\n");

    const customPrompt = details.prompt?.trim();
    const userPrompt = customPrompt
      ? `${customPrompt}\n\nDocument type: ${documentType}\nTone: ${tone}\nLength: ${length}\nJurisdiction: ${details.jurisdiction || "Philippines"}\n${detailsText}`
      : `Generate a complete ${documentType} (${tone} tone, ${length} length) with these details:\n${detailsText || "Use standard Philippine legal format with [PLACEHOLDER] for missing details."}`;

    const messages = [
      { role: "system" as const, content: DOCUMENT_SYSTEM_PROMPT },
      { role: "user" as const, content: userPrompt },
    ];

    const aiContent = await generateCompletion(messages, { maxTokens: 6000, temperature: 0.3 });

    if (aiContent && aiContent.length > 100) {
      return aiContent;
    }
  } catch (err) {
    console.error("AI generation error, falling back to local template:", err);
  }

  // Fall back to local templates
  const localKey = TEMPLATE_KEY_MAP[typeKey] || TEMPLATE_KEY_MAP[documentType] || null;
  if (localKey && DOCUMENT_TEMPLATES[localKey]) {
    return DOCUMENT_TEMPLATES[localKey](details);
  }

  // Generic fallback
  return `${documentType.toUpperCase()}

[Generated: ${new Date().toLocaleDateString("en-PH", { dateStyle: "long" })}]
[Jurisdiction: ${details.jurisdiction || "Republic of the Philippines"}]

CONTENTS:

[This is a template for a ${documentType}.]
[Please replace all [BRACKETED] items with the appropriate information.]
[Ensure compliance with Philippine legal requirements and the Rules of Court.]

---

This document was generated by JusConsultus AI as a starting template.
Please review and edit all content before use.
Consult a licensed Philippine attorney for legal advice.`;
}

export async function POST(req: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const body = await req.json();
    const { documentType, templateId, details, tone, length, jurisdiction, prompt: userPrompt } = body;

    const docType = documentType || templateId || "general";

    const detailsObj: TemplateData = {
      ...(typeof details === "object" ? details : {}),
      jurisdiction: jurisdiction || "Philippines",
      prompt: userPrompt || "",
    };

    const content = await generateDocument(docType, detailsObj, tone || "formal", length || "medium");

    return NextResponse.json({ content });
  } catch (error) {
    console.error("Document generate API error:", error);
    return NextResponse.json({ error: "Failed to generate document" }, { status: 500 });
  }
}
